name: Check Python Formatting

on:
  pull_request:

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47

      - name: List changed files
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: echo $CHANGED_FILES

      - name: Init ruff and print version
        uses: astral-sh/ruff-action@v3
        with:
          args: --version
      - name: Check python format
        uses: astral-sh/ruff-action@v3
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          args: format --check --diff
          src: $CHANGED_FILES
      - name: Check python syntax
        uses: astral-sh/ruff-action@v3
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          args: check --diff
          src: $CHANGED_FILES
