name: Check Python Formatting

on:
  pull_request:
    types: [ready_for_review]
jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v5

      - name: Init ruff and print version
        uses: astral-sh/ruff-action@v3
        with:
          args: --version
      - name: Check python format
        run: ruff format --check
      - name: Check python syntax
        run: ruff check
